# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

persistence true
persistence_location /var/lib/mosquitto/
allow_anonymous true

# add printing to stdout
log_dest stdout

include_dir /home/npluta/repositories/private/workspace-telemetry-system/zephyr/samples/net/mqtt_publisher/mosquitto/conf.d
